### PR TITLE
Allow setting build and launch cache paths

### PR DESCRIPTION
**Pull request by iocanel**
This pull request makes the build cache and launch cache volume paths configurable.

### CODE REVIEW

**Comment by iocanel** [comment]
@cmoulliard: I think that this is something that you wanted to use the other day in order to cache the m2 repository. I think that this is prerequisite.

**Comment by cmoulliard** [comment]
Can you please update the README file to add as new example, this one able to configure the cache ? @iocanel

**Review by cmoulliard — COMMENTED** [review]
Can you please update the README file to add as new example, this one able to configure the cache ?

**Comment by BarDweller** [comment]
Not sure if this is doing what you expect, build & launch cache locations are used by buildpacks lifecycle binaries during execution to store things that should be reinflated if a subsequent build of the same app is performed.. so if you mapped the .m2 dir into one of those, it might get totally nuked by buildpacks.. 

We could do a bind mount of m2 to the container, but from previous containerized build projects I remember being told that .m2 should not be shared concurrently, as it has no protection against concurrent updates (eg, buildpacks building using it, while you use it locally in another shell).. 

I'm leaning toward closing this one, but I am curious to know if the intent was to allow sharing of a dev's m2 dir into the build, if so, I don't think we can (safely) do that, but we could offer an extra api to allow additional bind mounts to the lifecycle phases configured by the end-user (at their own risk). 

If so, we can raise a feature for that, and address it appropriately

**Comment by BarDweller** [comment]
Closing this as not planned.

**Pull request closed without merging**
